/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export const US_CITIES = [
  { city: "New York", state: "NY" },
  { city: "Los Angeles", state: "CA" },
  { city: "Chicago", state: "IL" },
  { city: "Houston", state: "TX" },
  { city: "Phoenix", state: "AZ" },
  { city: "Philadelphia", state: "PA" },
  { city: "San Antonio", state: "TX" },
  { city: "San Diego", state: "CA" },
  { city: "Dallas", state: "TX" },
  { city: "San Jose", state: "CA" },
  { city: "Austin", state: "TX" },
  { city: "Jacksonville", state: "FL" },
  { city: "Fort Worth", state: "TX" },
  { city: "Columbus", state: "OH" },
  { city: "San Francisco", state: "CA" },
  { city: "Charlotte", state: "NC" },
  { city: "Indianapolis", state: "IN" },
  { city: "Seattle", state: "WA" },
  { city: "Denver", state: "CO" },
  { city: "Washington", state: "DC" },
  { city: "Boston", state: "MA" },
  { city: "El Paso", state: "TX" },
  { city: "Nashville", state: "TN" },
  { city: "Detroit", state: "MI" },
  { city: "Oklahoma City", state: "OK" },
  { city: "Portland", state: "OR" },
  { city: "Las Vegas", state: "NV" },
  { city: "Memphis", state: "TN" },
  { city: "Louisville", state: "KY" },
  { city: "Baltimore", state: "MD" },
  { city: "Milwaukee", state: "WI" },
  { city: "Albuquerque", state: "NM" },
  { city: "Tucson", state: "AZ" },
  { city: "Fresno", state: "CA" },
  { city: "Sacramento", state: "CA" },
  { city: "Mesa", state: "AZ" },
  { city: "Kansas City", state: "MO" },
  { city: "Atlanta", state: "GA" },
  { city: "Long Beach", state: "CA" },
  { city: "Colorado Springs", state: "CO" },
  { city: "Raleigh", state: "NC" },
  { city: "Miami", state: "FL" },
  { city: "Virginia Beach", state: "VA" },
  { city: "Omaha", state: "NE" },
  { city: "Oakland", state: "CA" },
  { city: "Minneapolis", state: "MN" },
  { city: "Tulsa", state: "OK" },
  { city: "Arlington", state: "TX" },
  { city: "New Orleans", state: "LA" },
  { city: "Wichita", state: "KS" },
  { city: "Cleveland", state: "OH" },
  { city: "Tampa", state: "FL" },
  { city: "Bakersfield", state: "CA" },
  { city: "Aurora", state: "CO" },
  { city: "Anaheim", state: "CA" },
  { city: "Honolulu", state: "HI" },
  { city: "Santa Ana", state: "CA" },
  { city: "Riverside", state: "CA" },
  { city: "Corpus Christi", state: "TX" },
  { city: "Lexington", state: "KY" },
  { city: "Henderson", state: "NV" },
  { city: "Stockton", state: "CA" },
  { city: "Saint Paul", state: "MN" },
  { city: "Cincinnati", state: "OH" },
  { city: "St. Louis", state: "MO" },
  { city: "Pittsburgh", state: "PA" },
  { city: "Greensboro", state: "NC" },
  { city: "Lincoln", state: "NE" },
  { city: "Anchorage", state: "AK" },
  { city: "Plano", state: "TX" },
  { city: "Orlando", state: "FL" },
  { city: "Irvine", state: "CA" },
  { city: "Newark", state: "NJ" },
  { city: "Durham", state: "NC" },
  { city: "Chula Vista", state: "CA" },
  { city: "Toledo", state: "OH" },
  { city: "Fort Wayne", state: "IN" },
  { city: "St. Petersburg", state: "FL" },
  { city: "Laredo", state: "TX" },
  { city: "Jersey City", state: "NJ" },
  { city: "Chandler", state: "AZ" },
  { city: "Madison", state: "WI" },
  { city: "Lubbock", state: "TX" },
  { city: "Scottsdale", state: "AZ" },
  { city: "Reno", state: "NV" },
  { city: "Buffalo", state: "NY" },
  { city: "Gilbert", state: "AZ" },
  { city: "Glendale", state: "AZ" },
  { city: "North Las Vegas", state: "NV" },
  { city: "Winston-Salem", state: "NC" },
  { city: "Chesapeake", state: "VA" },
  { city: "Norfolk", state: "VA" },
  { city: "Fremont", state: "CA" },
  { city: "Garland", state: "TX" },
  { city: "Irving", state: "TX" },
  { city: "Hialeah", state: "FL" },
  { city: "Richmond", state: "VA" },
  { city: "Boise", state: "ID" },
  { city: "Spokane", state: "WA" },
  { city: "Baton Rouge", state: "LA" }
];

export const NICHES = [
  { label: "Dentist", category: "healthcare.dentist" },
  { label: "Restaurant", category: "catering.restaurant" },
  { label: "Lawyer", category: "service.financial.lawyer" },
  { label: "Gym / Fitness", category: "leisure.sport.fitness" },
  { label: "Plumbing", category: "service.construction.plumber" },
  { label: "HVAC", category: "service.construction.hvac" },
  { label: "Roofing", category: "service.construction.roofing" },
  { label: "Auto Repair", category: "service.vehicle.repair" },
  { label: "Real Estate", category: "service.real_estate" },
  { label: "Marketing", category: "office.advertising" }
];
